export const myVar = 'This is my variable'

export const CONSTANTS = {
    BOT_TOKEN: process.env.VUE_APP_BOT_TOKEN,
    BOT_NAME: process.env.VUE_APP_BOT_NAME,
    NOMINATIM_SEARCH_ADDRESS_BY_TEXT_URL: process.env.VUE_APP_NOMINATIM_SEARCH_ADDRESS_BY_TEXT_URL,
    NOMINATIM_SEARCH_ADDRESS_BY_COORDS_URL: process.env.VUE_APP_NOMINATIM_SEARCH_ADDRESS_BY_COORDS_URL,
    BIRDAMLIK_EXPORT_EVENT_URL: process.env.VUE_APP_BIRDAMLIK_EXPORT_EVENT_URL,
    ROUTE_SEARCH_BY_COORDS_URL: process.env.VUE_APP_ROUTE_SEARCH_BY_COORDS_URL,
    ROUTE_SEARCH_BY_COORDS_KEY: 'OPENROUTE_SERVICE_KEY',
    ICON_PATH: '/img/',
    DRAWING_FEATURE_ID: -1999,
    USER_LOCATION_FEATURE_ID: -999,
    ICONS_URL: {
        1: require('../assets/icons/sos.png'),
        2: require('../assets/icons/ready_assist.png'),
        3: require('../assets/icons/water.png'),
        4: require('../assets/icons/food.png'),
        5: require('../assets/icons/hospital.png'),
        6: require('../assets/icons/doctor.png'),
        7: require('../assets/icons/blood_center.png'),
        8: require('../assets/icons/blood_donor.png'),
        9: require('../assets/icons/charity.png'),
        10: require('../assets/icons/attention.png'),
        11: require('../assets/icons/level.png'),
        12: require('../assets/icons/vet.png'),
    },
    ICON: {
        NEED_HELP: require('../assets/icons/sos.png'),
        NEED_HELP_CLUSTER: require('../assets/icons/sos.png'),
        READY_ASSIST: require('../assets/icons/ready_assist.png'),
        READY_ASSIST_CLUSTER: require('../assets/icons/ready_assist.png'),
        WATER: require('../assets/icons/water.png'),
        WATER_CLUSTER: require('../assets/icons/water.png'),
        FOOD: require('../assets/icons/food.png'),
        FOOD_CLUSTER: require('../assets/icons/food.png'),
        HEALTH_CARE_CENTER: require('../assets/icons/hospital.png'),
        HEALTH_CARE_CENTER_CLUSTER: require('../assets/icons/hospital.png'),
        DOCTOR: require('../assets/icons/doctor.png'),
        DOCTOR_CLUSTER: require('../assets/icons/doctor.png'),
        BLOOD_CENTER: require('../assets/icons/blood_center.png'),
        BLOOD_CENTER_CLUSTER: require('../assets/icons/blood_center.png'),
        BLOOD_DONOR: require('../assets/icons/blood_donor.png'),
        BLOOD_DONOR_CLUSTER: require('../assets/icons/blood_donor.png'),
        CHARITY: require('../assets/icons/charity.png'),
        CHARITY_CLUSTER: require('../assets/icons/charity.png'),
        ATTENTION: require('../assets/icons/attention.png'),
        ATTENTION_CLUSTER: require('../assets/icons/attention.png'),
        DRIVER: require('../assets/icons/level.png'),
        DRIVER_CLUSTER: require('../assets/icons/level.png'),
        VET: require('../assets/icons/vet.png'),
        VET_CLUSTER: require('../assets/icons/vet.png'),
        START_ROUTE_POINT: require('../assets/icons/start_route_point.png'),
        FINISH_ROUTE_POINT: require('../assets/icons/finish_route_point.png'),
    },
    ROLES: [
        {id: 1, name: 'System administrator'},
        {id: 2, name: 'Administrator'},
        {id: 3, name: 'Moderator'},
        {id: 4, name: 'User'},
        {id: 5, name: 'Trusted User'},
    ],
    ROLE: {
        SYSTEM_ADMINISTRATOR: 1,
        ADMINISTRATOR: 2,
        MODERATOR: 3,
        USER: 4,
        TRUSTED_USER: 5
    },
    AUTH_TYPE: {
        TELEGRAM: 1,
        FACEBOOK: 2,
        GOOGLE: 3,
        EMAIL_PASSWORD: 4,
        CUSTOM: 5,
        // 2: {name: "FACEBOOK", value: 2},
        // 3: {name: "GOOGLE", value: 3},
        // 4: {name: "EMAIL_PASSWORD", value: 4},
        // 5: {name: "CUSTOM", value: 5}
    },
    FEATURE_TYPE: {
        CIRCLE: 'Circle',
        LINE_STRING: 'LineString',
        POLYGON: 'Polygon',
        MULTIPOLYGON: 'MultiPolygon',
        POINT: 'Point'
    },
    EVENT_ACTION_TYPE: {
        USER_WANT_COMMUNICATION: 10,
        USER_RESPONSED: 11
    },

    APP_STATE: {
        DEFAULT: 'default',
        ADD_EVENT: 'addEvent',
        EDIT_EVENT: 'editEvent',
        CANCEL_ADD_EVENT: 'cancelAddEvent',
        CANCEL_EDIT_EVENT: 'cancelEditEvent'
    },
    PERMISSION: {
        ADD_EVENT: 'add_event',
        EDIT_EVENT: 'edit_event',
        DELETE_EVENT: 'delete_event',
        RESPONSE_TO_HELP: 'response_to_help',
        BLOCK_USER: 'block_user',
        MODERATE_EVENT: 'moderate_event',
        EDIT_EVENT_DURATION: 'edit_event_duration',
        PREVIEW_EVENT_EDITING: 'preview_event_edit',

        EDIT_EVENT_CATEGORY: 'edit_event_category',
        EDIT_EVENT_NAME: 'edit_event_name',
        EDIT_EVENT_DESCRIPTION: 'edit_event_description',
        EDIT_EVENT_START_DATE: 'edit_event_start_date',
        EDIT_EVENT_END_DATE: 'edit_event_end_date',
        EDIT_EVENT_COORDINATES: 'edit_event_coordinates',
        EDIT_EVENT_NAME_VISIBILITY: 'edit_event_name_visibility',
        EDIT_EVENT_DESCRIPTION_VISIBILITY: 'edit_event_description_visibility',

        VIEW_ADMIN_PANEL: 'view_admin_panel',
        VIEW_ADMIN_DASHBOARD: 'view_admin_dashboard',
        VIEW_ADMIN_EVENTS: 'view_admin_events',
        VIEW_ADMIN_USERS: 'view_admin_users',
        VIEW_ADMIN_ROLES: 'view_admin_roles',
        VIEW_ADMIN_LAYERS: 'view_admin_layers',
    },
    EVENT_CATEGORY: {
        NEED_HELP: 1,
        READY_ASSIST: 2,
        WATER: 3,
        FOOD: 4,
        HEALTH_CARE_CENTER: 5,
        DOCTOR: 6,
        BLOOD_CENTER: 7,
        BLOOD_DONOR: 8,
        CHARITY: 9,
        ATTENTION: 10,
        DRIVER: 11,
        VET: 12
    },
    FILTER_STATUS: {
        ACTUAL: 1,
        ALL: 2,
        OWN: 3,
        MODERATING: 4
    },
}
